# Generated by Django 5.2.7 on 2026-03-10 19:29

import django.db.models.deletion
import rrhh.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=15, unique=True)),
                ('apellido', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('nacionalidad', models.CharField(blank=True, max_length=100)),
                ('sexo', models.CharField(blank=True, choices=[('masculino', 'Masculino'), ('femenino', 'Femenino'), ('otro', 'Otro')], max_length=20)),
                ('ciudad', models.CharField(blank=True, max_length=100)),
                ('barrio', models.CharField(blank=True, max_length=100)),
                ('calle', models.CharField(blank=True, max_length=120)),
                ('numero', models.CharField(blank=True, max_length=20)),
                ('estado_civil', models.CharField(blank=True, choices=[('soltero', 'Soltero/a'), ('casado', 'Casado/a'), ('divorciado', 'Divorciado/a'), ('viudo', 'Viudo/a'), ('union', 'Unión convivencial')], max_length=30)),
                ('legajo', models.CharField(max_length=20, unique=True)),
                ('turno', models.CharField(blank=True, choices=[('manana', 'Mañana'), ('tarde', 'Tarde'), ('noche', 'Noche')], max_length=10)),
                ('categoria', models.PositiveIntegerField(blank=True, null=True)),
                ('condicion', models.CharField(blank=True, choices=[('contratado', 'Contratado'), ('planta', 'Planta Permanente'), ('voluntariado', 'Voluntariado'), ('otro', 'Otro')], max_length=20)),
                ('fecha_inicio_contrato', models.DateField(blank=True, null=True)),
                ('fecha_fin_contrato', models.DateField(blank=True, null=True)),
                ('inicio_actividad', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('correo', models.EmailField(blank=True, max_length=254)),
                ('celular', models.CharField(blank=True, max_length=30)),
                ('contacto_emergencia_nombre', models.CharField(blank=True, max_length=150)),
                ('contacto_emergencia_cel', models.CharField(blank=True, max_length=30)),
                ('foto', models.ImageField(blank=True, null=True, upload_to=rrhh.models.foto_path)),
                ('antiguedad_anios', models.PositiveIntegerField(default=0, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Feriado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha', models.DateField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='IndumentariaStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenda', models.CharField(max_length=100)),
                ('talle', models.CharField(max_length=20)),
                ('cantidad', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ModuloSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('url_acceso', models.CharField(max_length=100)),
                ('icono', models.CharField(default='fa-cube', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentoEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=120)),
                ('archivo', models.FileField(upload_to=rrhh.models.documento_path)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='rrhh.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='Conyuge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(blank=True, max_length=15)),
                ('nombre', models.CharField(blank=True, max_length=100)),
                ('apellido', models.CharField(blank=True, max_length=100)),
                ('empleado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='conyuge', to='rrhh.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='EntregaIndumentaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('prenda', models.CharField(max_length=100)),
                ('talle', models.CharField(max_length=20)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('comprobante', models.FileField(blank=True, null=True, upload_to=rrhh.models.comprobante_path)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rrhh.empleado')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Hijo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(blank=True, max_length=15)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hijos', to='rrhh.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('LICENCIA', 'Licencia'), ('BAJA', 'Baja'), ('VACACIONES', 'Vacaciones'), ('ALTA', 'Alta'), ('INDUMENTARIA', 'Indumentaria'), ('SANCION', 'Sanción')], max_length=20)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('detalle', models.TextField(blank=True)),
                ('empleado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rrhh.empleado')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo_interno', models.CharField(blank=True, max_length=20)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subsectores', to='rrhh.sector')),
            ],
            options={
                'verbose_name': 'Sector',
                'verbose_name_plural': 'Sectores',
            },
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_jefe_area', models.BooleanField(default=False)),
                ('empleado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rrhh.empleado')),
                ('sistemas_habilitados', models.ManyToManyField(blank=True, to='rrhh.modulosistema')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
                ('sector_gestion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rrhh.sector')),
            ],
        ),
        migrations.AddField(
            model_name='empleado',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personal_sector', to='rrhh.sector'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='subsector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personal_subsector', to='rrhh.sector'),
        ),
        migrations.CreateModel(
            name='SolicitudCuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo_acceso', models.TextField()),
                ('permiso_vacaciones', models.BooleanField(default=False)),
                ('permiso_asistencia', models.BooleanField(default=False)),
                ('permiso_horas_extras', models.BooleanField(default=False)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('creada', 'Cuenta Creada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20)),
                ('empleado_a_habilitar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rrhh.empleado')),
                ('jefe_solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vacacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.PositiveIntegerField(default=2026)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('fecha_reintegro', models.DateField(blank=True, null=True)),
                ('dias_habiles', models.PositiveIntegerField(default=0, editable=False)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('visto_bueno', 'Avalado por Jefe'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacaciones', to='rrhh.empleado')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmpleadoTalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_prenda', models.CharField(choices=[('PANTALON', 'Pantalón'), ('AMBO', 'Ambo'), ('CHOMBA', 'Chomba'), ('CAMISA', 'Camisa'), ('BORCEGO', 'Borcego'), ('ZAPATOS', 'Zapatos de Seguridad'), ('CAMPERA', 'Campera / Abrigo'), ('OTRO', 'Otro...')], max_length=50)),
                ('talle', models.CharField(max_length=20)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talles', to='rrhh.empleado')),
            ],
            options={
                'unique_together': {('empleado', 'tipo_prenda')},
            },
        ),
    ]
