# Generated by Django 5.2.7 on 2026-03-11 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0002_categoria_motivobaja_tipocontrato_tipomovimiento_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TipoContrato',
            new_name='CondicionLaboral',
        ),
        migrations.AlterModelOptions(
            name='condicionlaboral',
            options={'verbose_name_plural': 'Condiciones Laborales'},
        ),
        migrations.AlterModelOptions(
            name='sector',
            options={'verbose_name': 'Sector/Subsector', 'verbose_name_plural': 'Sectores y Subsectores'},
        ),
        migrations.AlterField(
            model_name='empleado',
            name='nacionalidad',
            field=models.CharField(blank=True, default='Argentina', max_length=100),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empleados_sector', to='rrhh.sector'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='subsector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empleados_subsector', to='rrhh.sector'),
        ),
    ]
