# Generated by Django 5.2.7 on 2026-03-13 11:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0004_alter_sector_options_alter_categoria_nombre_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroAsistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('estado', models.CharField(choices=[('PRESENTE', 'Presente'), ('TARDANZA', 'Tardanza'), ('AUSENTE_SIN_AVISO', 'Ausente sin Aviso'), ('AUSENTE_CON_AVISO', 'Ausente con Aviso')], default='PRESENTE', max_length=20)),
                ('motivo_ausencia', models.TextField(blank=True, null=True, verbose_name='Motivo (si aplica)')),
                ('adjunto_justificativo', models.FileField(blank=True, null=True, upload_to='asistencia/justificativos/%Y/%m/%d/', verbose_name='Certificado/Justificativo (PDF o Imagen)')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='rrhh.empleado')),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
            ],
            options={
                'verbose_name': 'Registro de Asistencia',
                'verbose_name_plural': 'Registros de Asistencia',
                'ordering': ['-fecha', 'empleado__apellido'],
                'unique_together': {('fecha', 'empleado')},
            },
        ),
    ]
