# Generated by Django 5.2.7 on 2026-03-15 19:09

import django.db.models.deletion
import rrhh.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0005_registroasistencia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='registroasistencia',
            name='horas_extras',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='registroasistencia',
            name='adjunto_justificativo',
            field=models.FileField(blank=True, null=True, upload_to=rrhh.models.asistencia_path, verbose_name='Certificado/Justificativo'),
        ),
        migrations.CreateModel(
            name='RegistroHoraExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha de la Actividad')),
                ('hora_inicio', models.TimeField(verbose_name='Hora Incial')),
                ('hora_fin', models.TimeField(verbose_name='Hora Final')),
                ('horas_totales', models.DecimalField(decimal_places=2, help_text='Calculado automáticamente', max_digits=5, verbose_name='Total Horas')),
                ('motivo_actividad', models.TextField(verbose_name='Detalle de la Actividad')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horas_extras', to='rrhh.empleado')),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
            ],
            options={
                'verbose_name': 'Registro de Hora Extra',
                'verbose_name_plural': 'Registros de Horas Extras',
                'ordering': ['-fecha', 'empleado__apellido'],
            },
        ),
    ]
