# Generated by Django 5.2.7 on 2026-03-15 22:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0006_registroasistencia_horas_extras_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='vacacion',
            name='aprobado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacaciones_aprobadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vacacion',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacaciones_creadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
