# Generated by Django 5.2.7 on 2026-03-16 11:54

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0007_vacacion_aprobado_por_alter_vacacion_usuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransaccionBancoHoras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=datetime.date.today)),
                ('cantidad', models.DecimalField(decimal_places=2, help_text='Positivo para suma, Negativo para resta', max_digits=6)),
                ('tipo', models.CharField(choices=[('HORA_EXTRA', 'Horas Extras Realizadas'), ('FRANCO', 'Día de Franco Tomado'), ('PAGO', 'Horas Cobradas / Pagas'), ('AJUSTE', 'Ajuste Manual')], max_length=20)),
                ('referencia_id', models.PositiveIntegerField(blank=True, help_text='ID del registro relacionado (si aplica)', null=True)),
                ('detalle', models.TextField(blank=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacciones_banco', to='rrhh.empleado')),
            ],
            options={
                'verbose_name': 'Transacción de Banco de Horas',
                'verbose_name_plural': 'Transacciones de Banco de Horas',
                'ordering': ['-fecha', '-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='FrancoProgramado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='francos_programados', to='rrhh.empleado')),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Franco Programado',
                'verbose_name_plural': 'Francos Programados',
                'ordering': ['-fecha'],
                'unique_together': {('empleado', 'fecha')},
            },
        ),
    ]
