# Generated by Django 5.2.7 on 2026-03-25 18:31

import datetime
import django.db.models.deletion
import rrhh.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0008_transaccionbancohoras_francoprogramado'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaLicencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('requiere_seguimiento_medico', models.BooleanField(default=False)),
                ('requiere_certificado', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Categoría de Licencia',
                'verbose_name_plural': 'Categorías de Licencia',
            },
        ),
        migrations.CreateModel(
            name='SolicitudLicencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_desde', models.DateField()),
                ('fecha_hasta', models.DateField()),
                ('estado', models.CharField(choices=[('Pendiente_Certificado', 'Pendiente de Certificado (Provisorio)'), ('Entregado', 'Certificado Entregado'), ('Aprobada', 'Aprobada'), ('Rechazada', 'Rechazada')], default='Pendiente_Certificado', max_length=30)),
                ('adjunto_pdf', models.FileField(blank=True, null=True, upload_to=rrhh.models.asistencia_path)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_licencia', to='rrhh.empleado')),
            ],
            options={
                'verbose_name': 'Solicitud de Licencia',
                'verbose_name_plural': 'Solicitudes de Licencias',
                'ordering': ['-fecha_desde', 'empleado__apellido'],
                'permissions': [('can_audit_licencias', 'Puede auditar, seguir y aprobar licencias')],
            },
        ),
        migrations.CreateModel(
            name='SeguimientoMedico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_consulta', models.DateField(default=datetime.date.today)),
                ('medico', models.CharField(max_length=150)),
                ('evolucion', models.TextField()),
                ('proximo_control', models.DateField(blank=True, null=True)),
                ('es_alta_medica', models.BooleanField(default=False)),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to='rrhh.solicitudlicencia')),
            ],
            options={
                'verbose_name': 'Seguimiento Médico',
                'verbose_name_plural': 'Seguimientos Médicos',
                'ordering': ['-fecha_consulta'],
            },
        ),
        migrations.CreateModel(
            name='TipoLicencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('limite_dias_anual', models.PositiveIntegerField(help_text='Límite de días por año calendario')),
                ('es_dias_habiles', models.BooleanField(default=True, help_text='Si es True, descuenta sábados, domingos y feriados')),
                ('detalle', models.TextField(blank=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipos', to='rrhh.categorialicencia')),
            ],
            options={
                'verbose_name': 'Tipo de Licencia',
                'verbose_name_plural': 'Tipos de Licencia',
            },
        ),
        migrations.AddField(
            model_name='solicitudlicencia',
            name='tipo_licencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rrhh.tipolicencia'),
        ),
    ]
