# Generated by Django 5.2.7 on 2026-03-26 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0009_categorialicencia_solicitudlicencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudlicencia',
            name='motivo_rechazo',
            field=models.TextField(blank=True, verbose_name='Motivo de Rechazo'),
        ),
    ]
