# Generated by Django 5.2.7 on 2026-03-26 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0010_solicitudlicencia_motivo_rechazo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroasistencia',
            name='estado',
            field=models.CharField(choices=[('PRESENTE', 'Presente'), ('TARDANZA', 'Tardanza'), ('AUSENTE_SIN_AVISO', 'Ausente sin Aviso'), ('AUSENTE_CON_AVISO', 'Ausente con Aviso'), ('LICENCIA', 'Licencia Médica/Gremial (Bloqueado)')], default='PRESENTE', max_length=20),
        ),
    ]
