# Generated by Django 5.2.7 on 2026-03-26 19:38

import rrhh.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0011_alter_registroasistencia_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacacion',
            name='adjunto_solicitud',
            field=models.FileField(blank=True, null=True, upload_to=rrhh.models.vacaciones_path),
        ),
        migrations.AlterField(
            model_name='solicitudlicencia',
            name='adjunto_pdf',
            field=models.FileField(blank=True, null=True, upload_to=rrhh.models.licencia_path),
        ),
    ]
