# Generated by Django 5.2.7 on 2026-03-27 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0012_vacacion_adjunto_solicitud_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroasistencia',
            name='bloqueado',
            field=models.BooleanField(default=False, verbose_name='Bloqueado por Cierre de Mes'),
        ),
        migrations.AlterField(
            model_name='registroasistencia',
            name='estado',
            field=models.CharField(choices=[('PRESENTE', 'Presente'), ('TARDANZA', 'Tardanza'), ('AUSENTE_SIN_AVISO', 'Ausente sin Aviso'), ('AUSENTE_CON_AVISO', 'Ausente con Aviso'), ('LICENCIA', 'Licencia Médica/Gremial (Bloqueado)'), ('SANCION', 'Sanción Disciplinaria')], default='PRESENTE', max_length=20),
        ),
    ]
