# Generated by Django 5.2.7 on 2026-03-27 18:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh', '0013_registroasistencia_bloqueado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroasistencia',
            name='fecha',
            field=models.DateField(default=datetime.date.today, verbose_name='Fecha de Registro'),
        ),
    ]
