# Generated by Django 5.2.7 on 2026-03-11 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('innovacion', '0001_initial'),
        ('rrhh', '0004_alter_sector_options_alter_categoria_nombre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudacceso',
            name='observaciones',
        ),
        migrations.AddField(
            model_name='solicitudacceso',
            name='nivel_acceso',
            field=models.CharField(choices=[('ESTANDAR', 'Usuario Estándar'), ('ADMIN_DEP', 'responsable de sector'), ('SUPERVISOR', 'Supervisor'), ('SUPERADMIN', 'Superadministrador')], default='ESTANDAR', max_length=20),
        ),
        migrations.AlterField(
            model_name='solicitudacceso',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rrhh.empleado'),
        ),
        migrations.AlterField(
            model_name='solicitudacceso',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PROCESADO', 'Procesado'), ('RECHAZADO', 'Solicitud Rechazada')], default='PENDIENTE', max_length=20),
        ),
    ]
