# Generated by Django 5.2.7 on 2026-03-12 10:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('innovacion', '0002_remove_solicitudacceso_observaciones_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FuncionSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_visible', models.CharField(max_length=100)),
                ('codigo_interno', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SistemaMunicipal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.SlugField(unique=True)),
                ('icono', models.CharField(default='fas fa-desktop', max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='solicitudacceso',
            name='nivel_acceso',
        ),
        migrations.CreateModel(
            name='PerfilAcceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esta_activo', models.BooleanField(default=True)),
                ('observaciones', models.TextField(blank=True)),
                ('funciones', models.ManyToManyField(blank=True, to='innovacion.funcionsistema')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_innovacion', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='funcionsistema',
            name='sistema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funciones', to='innovacion.sistemamunicipal'),
        ),
    ]
