# Generated by Django 5.2.7 on 2026-03-12 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('innovacion', '0003_funcionsistema_sistemamunicipal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilacceso',
            name='puede_solicitar',
            field=models.BooleanField(default=True, help_text='Habilita al usuario para cargar vacaciones/tramites'),
        ),
    ]
