# Generated by Django 5.2.7 on 2026-03-13 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('innovacion', '0004_perfilacceso_puede_solicitar'),
        ('rrhh', '0005_registroasistencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilacceso',
            name='empleado',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuario_sistema', to='rrhh.empleado'),
        ),
    ]
