# Generated by Django 5.x on 2026-03-13
from django.db import migrations

def crear_datos_iniciales(apps, schema_editor):
    # Obtenemos los modelos desde el historial de la app
    Sistema = apps.get_model('innovacion', 'SistemaMunicipal')
    Funcion = apps.get_model('innovacion', 'FuncionSistema')

    # 1. CREACIÓN DE SISTEMAS
    rrhh, _ = Sistema.objects.get_or_create(
        codigo='rrhh',
        defaults={'nombre': 'Recursos Humanos', 'icono': 'fas fa-users'}
    )
    
    innovacion, _ = Sistema.objects.get_or_create(
        codigo='innovacion',
        defaults={'nombre': 'Innovación y Sistemas', 'icono': 'fas fa-laptop-code'}
    )

    # 2. CREACIÓN DE FUNCIONES (Permisos que usa el decorador @tiene_funcion)
    lista_funciones = [
        # Funciones para el módulo de RRHH
        (rrhh, 'Tomar Asistencia (Jefes)', 'rrhh_tomar_asistencia'),
        (rrhh, 'Ver Listado de Personal', 'rrhh_ver_personal'),
        (rrhh, 'Administrar RRHH (Full)', 'rrhh_admin_total'),
        
        # Funciones para el módulo de Innovación
        (innovacion, 'Gestionar Accesos y Usuarios', 'acceso_innovacion_admin'),
        (innovacion, 'Ver Solicitudes de Cuenta', 'innovacion_ver_solicitudes'),
    ]

    for sistema, nombre, codigo in lista_funciones:
        Funcion.objects.get_or_create(
            codigo_interno=codigo,
            defaults={
                'sistema': sistema,
                'nombre_visible': nombre
            }
        )

def eliminar_datos_iniciales(apps, schema_editor):
    # Borra los sistemas creados (esto borrará las funciones por CASCADE si existe)
    Sistema = apps.get_model('innovacion', 'SistemaMunicipal')
    Sistema.objects.filter(codigo__in=['rrhh', 'innovacion']).delete()

class Migration(migrations.Migration):

    dependencies = [
        # IMPORTANTE: Esta dependencia une el historial de migraciones
        ('innovacion', '0005_perfilacceso_empleado'),
    ]

    operations = [
        migrations.RunPython(crear_datos_iniciales, eliminar_datos_iniciales),
    ]